"""initial schema

Revision ID: 13cab1c6d55d
Revises: 
Create Date: 2026-03-30 01:11:52.954972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13cab1c6d55d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('manifest_id', sa.String(length=64), nullable=False),
    sa.Column('partner_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocation_events_manifest_id'), 'allocation_events', ['manifest_id'], unique=False)
    op.create_index(op.f('ix_allocation_events_order_id'), 'allocation_events', ['order_id'], unique=False)
    op.create_table('config_versions',
    sa.Column('config_version_hash', sa.String(length=64), nullable=False),
    sa.Column('config_yaml', sa.Text(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('inserted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('config_version_hash')
    )
    op.create_table('idempotency_records',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('input_snapshots',
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('input_hash')
    )
    op.create_table('sealed_manifests',
    sa.Column('manifest_id', sa.String(length=64), nullable=False),
    sa.Column('manifest_json', sa.Text(), nullable=False),
    sa.Column('trace_hash', sa.String(length=64), nullable=False),
    sa.Column('config_version_hash', sa.String(length=64), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('manifest_id')
    )
    op.create_index(op.f('ix_sealed_manifests_config_version_hash'), 'sealed_manifests', ['config_version_hash'], unique=False)
    op.create_index(op.f('ix_sealed_manifests_decided_at'), 'sealed_manifests', ['decided_at'], unique=False)
    op.create_index(op.f('ix_sealed_manifests_trace_hash'), 'sealed_manifests', ['trace_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sealed_manifests_trace_hash'), table_name='sealed_manifests')
    op.drop_index(op.f('ix_sealed_manifests_decided_at'), table_name='sealed_manifests')
    op.drop_index(op.f('ix_sealed_manifests_config_version_hash'), table_name='sealed_manifests')
    op.drop_table('sealed_manifests')
    op.drop_table('input_snapshots')
    op.drop_table('idempotency_records')
    op.drop_table('config_versions')
    op.drop_index(op.f('ix_allocation_events_order_id'), table_name='allocation_events')
    op.drop_index(op.f('ix_allocation_events_manifest_id'), table_name='allocation_events')
    op.drop_table('allocation_events')
    # ### end Alembic commands ###
